FROM registry.fedoraproject.org/fedora:42

RUN dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
    dnf update -y && \
    packages="steam gamescope vulkan-tools pipewire-pulseaudio gamemode bzip2-libs bzip2-libs.i686 glibc-langpack-en util-linux" && \
    dnf install -y $packages && \
    ln -s $(readlink -f /usr/lib/libbz2.so.1) /usr/lib/libbz2.so.1.0 || true && \
    ln -s $(readlink -f /usr/lib64/libbz2.so.1) /usr/lib64/libbz2.so.1.0 || true && \
    [ -f /etc/gshadow ] || touch /etc/gshadow && \
    chmod 600 /etc/gshadow || true && \
    groupadd -g 1000 steamgroup && \
    useradd -m -u 1000 -g 1000 steam && \
    mkdir -p /home/steam/.steam && \
    chown -R 1000:1000 /home/steam && \
    echo "Kontener Steam gotowy!"

USER steam
CMD ["/bin/bash"]
